<script setup lang="ts">
import { ref, onMounted, nextTick } from 'vue';
import { useI18n } from 'vue-i18n';
import {
  type FormInst,
  type FormItemInst,
  type FormItemRule,
  NForm,
  NFormItem,
  NInput,
  NButton,
  NSpace,
} from 'naive-ui';
import type { ErrorModel, UserCreate } from '@/openapi';
import { useApi } from '@/api';
import { useMessages } from '@/messages';
import { usePlatformData } from '@/platformData';
import { useAuthStore } from '@/stores';
import { useFormRules } from '@/formRules';
import router from '@/router';
import type { AxiosError } from 'axios';

const auth = useAuthStore();
const { message } = useMessages();
const { pfData } = usePlatformData();
const { authApi } = useApi();
const { t } = useI18n({ useScope: 'global' });

const initialFormModel = () => ({
  email: null,
  username: null,
  password: null,
  passwordRepeat: null,
  firstName: null,
  lastName: null,
  affiliation: null,
});

const formModel = ref<Record<string, string | null>>(initialFormModel());
const formRef = ref<FormInst | null>(null);
const { accountFormRules } = useFormRules();
const rPasswordFormItemRef = ref<FormItemInst | null>(null);
const firstInputRef = ref<HTMLInputElement | null>(null);
const loading = ref(false);

const passwordRepeatMatchRule = {
  validator: (rule: FormItemRule, value: string) =>
    !!value && !!formModel.value.password && value === formModel.value.password,
  message: () => t('models.user.formRulesFeedback.passwordRepNoMatch'),
  trigger: ['input', 'blur', 'password-input'],
};

function handlePasswordInput() {
  if (formModel.value.reenteredPassword) {
    rPasswordFormItemRef.value?.validate({ trigger: 'password-input' });
  }
}

async function registerUser() {
  try {
    await authApi.registerRegister({ userCreate: formModel.value as unknown as UserCreate })
    const activationNeeded = !pfData.value?.security?.usersActiveByDefault;
      const activationHint = activationNeeded
        ? t('register.activationNeededHint')
        : t('register.activationNotNeededHint');
      message.success(`${t('register.success')} ${activationHint}`, activationNeeded ? 20 : 5);
      // if no activation is needed, send verification link right away
      if (!activationNeeded && !pfData.value?.security?.closedMode) {
        authApi
          .verifyRequestToken({
            bodyVerifyRequestTokenAuthRequestVerifyTokenPost: {
              email: formModel.value.email || '',
            },
          })
          .then(() => {
            message.warning(t('account.manage.msgVerifyEmailWarning'));
          });
      }
      switchToLogin();
  } catch (e) {
    /**
       * Unfortunately, the errors returned by the endpoints generated by
       * FastAPI-Users have a weird custom model that we have to handle here...
       */
      const error = e as AxiosError;
      if (error.response) {
        const data = error.response.data as ErrorModel;
        if (error.response.status === 403) {
          message.error(t('errors.csrf'));
        } else if (data.detail === 'REGISTER_USER_ALREADY_EXISTS') {
          message.error(t('register.errors.emailAlreadyRegistered'));
        } else if (data.detail === 'REGISTER_USERNAME_ALREADY_EXISTS') {
          message.error(t('register.errors.usernameAlreadyRegistered'));
        } else if (data.detail && (data.detail as Record<string, string>).code === 'REGISTER_INVALID_PASSWORD') {
          message.error(t('register.errors.weakPassword'));
        } else {
          message.error(t('errors.unexpected'));
        }
      } else {
        message.error(t('errors.unexpected'));
      }
  } finally {
    loading.value = false;
  }
}

function handleRegisterClick() {
  loading.value = true;
  formRef.value
    ?.validate((errors) => {
      !errors && registerUser();
    })
    .catch(() => {
      message.error(t('errors.followFormRules'));
      loading.value = false;
    });
}

function resetForm() {
  loading.value = false;
  formModel.value = initialFormModel();
  formRef.value?.restoreValidation();
}

function switchToLogin() {
  resetForm();
  auth.showLoginModal(undefined, { name: 'accountProfile' });
}

onMounted(() => {
  if (
    (auth.loggedIn && !auth.user?.isSuperuser) ||
    (pfData.value?.security?.closedMode && !auth.loggedIn)
  ) {
    router.push({ name: 'home' });
  }
  nextTick(() => {
    firstInputRef.value?.focus();
  });
});
</script>

<template>
  <h1 style="text-align: center">{{ $t('register.heading') }}</h1>
  <div class="form-container">
    <div class="content-block">
      <n-form
        ref="formRef"
        :model="formModel"
        :rules="accountFormRules"
        label-placement="top"
        label-width="auto"
        require-mark-placement="right-hanging"
      >
        <n-form-item path="email" :label="$t('models.user.email')">
          <n-input
            v-model:value="formModel.email"
            type="text"
            :placeholder="$t('models.user.email')"
            @keydown.enter.prevent
            :disabled="loading"
            ref="firstInputRef"
          />
        </n-form-item>
        <n-form-item path="username" :label="$t('models.user.username')">
          <n-input
            v-model:value="formModel.username"
            type="text"
            :placeholder="$t('models.user.username')"
            @keydown.enter.prevent
            :disabled="loading"
          />
        </n-form-item>
        <n-form-item path="password" :label="$t('models.user.password')">
          <n-input
            v-model:value="formModel.password"
            type="password"
            :placeholder="$t('models.user.password')"
            @input="handlePasswordInput"
            @keydown.enter.prevent
            :disabled="loading"
          />
        </n-form-item>
        <n-form-item
          ref="rPasswordFormItemRef"
          first
          path="passwordRepeat"
          :rule="accountFormRules.passwordRepeat.concat([passwordRepeatMatchRule])"
          :label="$t('register.repeatPassword')"
        >
          <n-input
            v-model:value="formModel.passwordRepeat"
            type="password"
            :disabled="!formModel.password || loading"
            :placeholder="$t('register.repeatPassword')"
            @keydown.enter.prevent
          />
        </n-form-item>
        <n-form-item path="firstName" :label="$t('models.user.firstName')">
          <n-input
            v-model:value="formModel.firstName"
            type="text"
            :placeholder="$t('models.user.firstName')"
            @keydown.enter.prevent
            :disabled="loading"
          />
        </n-form-item>
        <n-form-item path="lastName" :label="$t('models.user.lastName')">
          <n-input
            v-model:value="formModel.lastName"
            type="text"
            :placeholder="$t('models.user.lastName')"
            @keydown.enter.prevent
            :disabled="loading"
          />
        </n-form-item>
        <n-form-item path="affiliation" :label="$t('models.user.affiliation')">
          <n-input
            v-model:value="formModel.affiliation"
            type="text"
            :placeholder="$t('models.user.affiliation')"
            @keyup.enter="() => handleRegisterClick()"
            :disabled="loading"
          />
        </n-form-item>
      </n-form>

      <n-space vertical :size="12" style="margin-top: 1rem">
        <n-button
          block
          type="primary"
          @click="handleRegisterClick"
          :loading="loading"
          :disabled="loading"
        >
          {{ $t('register.register') }}
        </n-button>
        <n-button secondary block @click="switchToLogin">
          {{ $t('register.switchToLogin') }}
        </n-button>
      </n-space>
    </div>
  </div>
</template>
