version: "3.9"

services:

  client:
    build:
      context: ./Tekst-Web
      target: prod
      platforms:
        - "linux/amd64"
      tags:
        - "tekst-web:custom"
      args:
        WEB_PATH: ${TEKST_WEB_PATH}
        SERVER_URL: ${TEKST_SERVER_URL}
        API_PATH: ${TEKST_API_PATH}
    environment:
      TEKST_SERVER_URL: ${TEKST_SERVER_URL}
      TEKST_API_PATH: ${TEKST_API_PATH}
    restart: always
    init: true
    ports:
      - "127.0.0.1:8087:80"
    networks:
      - api

  server:
    build:
      context: ./Tekst-API
      target: prod
      platforms:
        - "linux/amd64"
      tags:
        - "tekst-api:custom"
    restart: always
    init: true
    depends_on:
      - mongo
    env_file: .env
    networks:
      - api
      - db
    secrets:
      - tekst_security_init_admin_email
      - tekst_security_init_admin_password
      - tekst_db_user
      - tekst_db_password

  mongo:
    image: mongo:5.0.9
    restart: always
    init: true
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/tekst_db_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/tekst_db_password
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    networks:
      - db
    secrets:
      - tekst_db_user
      - tekst_db_password
    command: mongod --setParameter diagnosticDataCollectionEnabled=false

volumes:
  mongo_configdb:
  mongo_db:

networks:
  api:
  db:

secrets:
  tekst_security_init_admin_email:
    file: ./secrets/security_init_admin_email.txt
  tekst_security_init_admin_password:
    file: ./secrets/security_init_admin_password.txt
  tekst_db_user:
    file: ./secrets/db_user.txt
  tekst_db_password:
    file: ./secrets/db_password.txt
