version: "3.9"

services:

  webserver:
    image: "caddy:2.6-alpine"
    volumes:
      - "./deploy/caddy:/etc/caddy/:ro"
    ports:
      - "127.0.0.1:8008:80"
    networks:
      - front
      - back

  tekst-web:
    build:
      context: https://github.com/VedaWebProject/tekst-web.git
      target: prod
      platforms:
        - "linux/amd64"
      tags:
        - "tekst-web:custom"
      args:
        TEKST_CLIENT_PATH: ${TEKST_CLIENT_PATH}
        TEKST_SERVER_URL: ${TEKST_SERVER_URL}
        TEKST_API_PATH: ${TEKST_API_PATH}
    restart: always
    init: true
    env_file: [.env.client]
    networks:
      - front

  tekst-api:
    build:
      context: https://github.com/VedaWebProject/tekst-api.git
      target: prod
      platforms:
        - "linux/amd64"
      tags:
        - "tekst-api:custom"
    restart: always
    init: true
    depends_on:
      - mongo
    env_file: [.env.server]
    networks:
      - back

  mongo:
    image: mongo:5.0.9
    restart: always
    init: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - back

networks:
  front:
  back:
