version: "3.9"

services:

  client:
    build:
      context: ./Tekst-Web
      target: prod
      platforms:
        - "linux/amd64"
      tags:
        - "tekst-web:custom"
      args:
        WEB_PATH: ${TEKST_WEB_PATH}
        SERVER_URL: ${TEKST_SERVER_URL}
        API_PATH: ${TEKST_API_PATH}
    environment:
      TEKST_SERVER_URL: ${TEKST_SERVER_URL}
      TEKST_API_PATH: ${TEKST_API_PATH}
    volumes:
      - ${TEKST_WEB_STATIC_FILES}:/var/www/tekst/static/:ro
    restart: always
    init: true
    ports:
      - "127.0.0.1:8087:80"
    networks:
      - api

  server:
    build:
      context: ./Tekst-API
      target: prod
      platforms:
        - "linux/amd64"
      tags:
        - "tekst-api:custom"
    restart: always
    init: true
    depends_on:
      - mongo
      - es
    env_file: .env
    networks:
      - api
      - db
      - es
    secrets:
      - tekst_security_init_admin_email
      - tekst_security_init_admin_password
      - tekst_db_user
      - tekst_db_password

  mongo:
    image: mongo:7
    restart: always
    init: true
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/tekst_db_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/tekst_db_password
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    networks:
      - db
    secrets:
      - tekst_db_user
      - tekst_db_password
    command: mongod --setParameter diagnosticDataCollectionEnabled=false

  es:
    image: elasticsearch:8.12.2
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: 2G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    init: true
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - es
    environment:
      discovery.type: single-node
      xpack.security.enabled: false

volumes:
  mongo_configdb:
  mongo_db:
  es_data:

networks:
  api:
  db:
  es:

secrets:
  tekst_security_init_admin_email:
    file: ./secrets/security_init_admin_email.txt
  tekst_security_init_admin_password:
    file: ./secrets/security_init_admin_password.txt
  tekst_db_user:
    file: ./secrets/db_user.txt
  tekst_db_password:
    file: ./secrets/db_password.txt
