services:

  web:
    build:
      context: ./Tekst-Web
      target: prod
      args:
        WEB_PATH: ${TEKST_WEB_PATH:?TEKST_WEB_PATH not set in .env}
        SERVER_URL: ${TEKST_SERVER_URL:?TEKST_SERVER_URL not set in .env}
        API_PATH: ${TEKST_API_PATH:?TEKST_API_PATH not set in .env}
    image: "tekst-web:custom"
    environment:
      TEKST_SERVER_URL: ${TEKST_SERVER_URL:?TEKST_SERVER_URL not set in .env}
      TEKST_API_PATH: ${TEKST_API_PATH:?TEKST_API_PATH not set in .env}
    volumes:
      - ${TEKST_WEB_STATIC_DIR:?TEKST_WEB_STATIC_DIR not set in .env}:/var/www/tekst/static/:ro
    restart: always
    ports:
      - "127.0.0.1:8087:80"
    networks:
      - api

  api:
    build:
      context: ./Tekst-API
      target: prod
    image: "tekst-api:custom"
    restart: always
    init: true
    depends_on:
      - mongo
      - es
    env_file: .env
    networks:
      - api
      - mongo
      - es

  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TEKST_DB__USER}
      MONGO_INITDB_ROOT_PASSWORD: ${TEKST_DB__PASSWORD}
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    networks:
      - mongo
    command: mongod --setParameter diagnosticDataCollectionEnabled=false

  es:
    build:
      context: ./Tekst-API/deployment/elasticsearch
    image: "elasticsearch:tekst"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: 2G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - es

volumes:
  mongo_configdb:
  mongo_db:
  es_data:

networks:
  api:
  mongo:
  es:
