version: "3.9"

services:

  app:
    build:
      context: .
      target: prod
      platforms:
        - "linux/amd64"
    restart: always
    init: true
    depends_on:
      - mongo-prod
    ports:
      - 127.0.0.1:8000:8000
    env_file: [.env.prod.example]
    networks:
      - tr-backend
    profiles:
      - prod

  mongo-prod:
    image: mongo:5.0.9
    restart: always
    init: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      tr-backend:
        aliases:
          - mongo
    profiles:
      - prod

  mongo-dev:
    image: mongo:5.0.9
    restart: always
    init: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:27017:27017
    networks:
      tr-backend:
        aliases:
          - mongo
    profiles:
      - dev
      - test

  mongo-express:
    image: mongo-express
    restart: always
    init: true
    depends_on:
      - mongo-dev
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - tr-backend
    profiles:
      - dev

networks:
  tr-backend:
