# https://taskfile.dev

version: '3'

vars:

tasks:
  default:
    desc: Print this very list of available tasks
    vars:
      TEKST_VERSION:
        sh: task version
    cmds:
      - echo "This is Tekst client {{.TEKST_VERSION}}"
      - task --list
    silent: true

  version:
    desc: Print project version
    cmds:
      - npx -c 'node -p "process.env.npm_package_version"'
    silent: true

  dev:
    desc: Run development server
    cmds:
      - npm run dev
    silent: true
    ignore_error: true

  format:
    desc: Format code
    cmds:
      - npm run format

  lint:
    desc: Lint code
    cmds:
      - npm run lint

  build:
    desc: Build project
    cmds:
      - npm run build

  preview:
    desc: Preview project
    cmds:
      - npm run preview

  generate-openapi-client:
    cmds:
      - cmd: |
          TEMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'trtemp')
          OUTDIR="$TEMPDIR/tekst-ts-client"
          mkdir -p $OUTDIR
          cp .openapi-generator-ignore $OUTDIR
          docker run \
            --rm \
            -u 1000:1000 \
            -v $TEMPDIR:/local \
            openapitools/openapi-generator-cli:v6.3.0 \
              generate \
                -i https://raw.githubusercontent.com/VedaWebProject/Tekst-API/main/openapi.json \
                -g typescript-axios \
                -o /local/tekst-ts-client \
            #    --global-property skipFormModel=false \
                --additional-properties=typescriptThreePlus=true,useSingleRequestParameter=true \
                --skip-validate-spec
          mkdir -p ./src/openapi/
          rm -rf ./src/openapi/*
          cp -r $TEMPDIR/tekst-ts-client/* ./src/openapi/
          rm -rf $TEMPDIR
          npm run lint
