# https://taskfile.dev

version: "3"

vars:

tasks:
  default:
    desc: Print this very list of available tasks
    vars:
      TEXTRIG_VERSION:
        sh: task version
    cmds:
      - echo "This is TextRig server {{.TEXTRIG_VERSION}}"
      - task --list
    silent: true

  version:
    desc: Print project version
    cmds:
      - poetry run python3 -c "from textrig import __version__ as v; print(v, end='')"
    silent: true

  fix:
    desc: Run ruff and black to format code base and attempt to fix linting errors
    cmds:
      - poetry run black .
      - poetry run ruff check . --fix

  check:
    desc: Check code using ruff and black
    cmds:
      - poetry run ruff check . --extend-select N
      - poetry run black . --check

  run-tests:
    desc: Run test suite with pytest
    env:
      TEXTRIG_ENV_FILE: .env.test
    cmds:
      - poetry run coverage run -m pytest {{.CLI_ARGS}}
      - poetry run coverage report -m

  test:
    desc: Run tests, start and stop test services stack automatically
    cmds:
      - defer: {task: test-stack-down}
      - task: test-stack-up
      - task: wait-for-mongodb
      - task: run-tests

  run-app:
    desc: Run the application dev server (only for development!)
    env:
      TEXTRIG_DEV_MODE: true
    cmds:
      - poetry run python3 -m textrig run --reload

  run:
    desc: Run dev services stack and dev server, clean up afterwards
    cmds:
      - task: dev-stack-up
      - task: run-app
      - defer: {task: dev-stack-down}

  schema:
    desc: Export (development) OpenAPI schema to file openapi.json
    env:
      TEXTRIG_DEV_MODE: true
      TEXTRIG_LOG_LEVEL: ERROR
    cmds:
      - defer: {task: test-stack-down}
      - task: test-stack-up
      - task: wait-for-mongodb
      - poetry run python3 -m textrig schema -f

  pre-commit:
    desc: Run full pre-commit toolchain (fix code, test, code checks, export schema)
    cmds:
      - task: fix
      - task: test
      - task: check
      - task: schema

  clean:
    desc: Cleanup of generated files (won't work on Windows)
    cmds:
      - cmd: ruff clean
      - cmd: shopt -s globstar
      - cmd: |
          rm -rf \
            **/__pycache__ \
            .pytest_cache \
            .coverage \
            .venv/ \
            .env/ \
            dist \
            htmlcov \

  dev-stack-up:
    desc: Run dev services stack
    cmds:
      - docker compose -f dev/docker-compose.yml --profile dev -p textrig-dev up --detach

  dev-stack-down:
    desc: Stop dev stack and clean up all resources
    cmds:
      - docker compose -f dev/docker-compose.yml --profile dev -p textrig-dev down --volumes

  test-stack-up:
    desc: Run test services stack
    cmds:
      - docker compose -f dev/docker-compose.yml --profile test -p textrig-testing up --detach

  test-stack-down:
    desc: Stop test stack and clean up all resources
    cmds:
      - docker compose -f dev/docker-compose.yml --profile test -p textrig-testing down --volumes

  docker-build:
    desc: Build and tag production Docker image for app
    vars:
      TEXTRIG_VERSION:
        sh: task version
    cmds:
      - cmd: |
          docker build \
            --tag "textrig-server:latest" \
            --tag "textrig-server:{{.TEXTRIG_VERSION}}" \
            --target prod .

  wait-for-mongodb:
    internal: true
    cmd: printf "Waiting for MongoDB service"; while ! $(curl -f http://127.0.0.1:27017 > /dev/null 2>&1); do sleep 1; printf "."; done
