services:
  caddy:
    image: "caddy:2.10-alpine"
    restart: unless-stopped
    volumes:
      - "./caddy:/etc/caddy/:ro"
      - "./static:/var/www/tekst/static/:ro"
    network_mode: "host"
    profiles:
      - dev

  mongo:
    image: mongo:8
    restart: unless-stopped
    init: true
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - devstack
    profiles:
      - dev
      - test
    command: mongod --setParameter diagnosticDataCollectionEnabled=false

  es:
    build:
      dockerfile_inline: |
        FROM docker.elastic.co/elasticsearch/elasticsearch:9.0.1
        RUN elasticsearch-plugin install analysis-icu
    image: "elasticsearch:tekst"
    deploy:
      resources:
        limits:
          memory: 2G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    init: true
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    environment:
      ES_SETTING_DISCOVERY_TYPE: single-node
      ES_SETTING_XPACK_SECURITY_ENABLED: false
      ES_JAVA_OPTS: "-XX:-AlwaysPreTouch"
    profiles:
      - dev
      - test

  mongo-express:
    image: mongo-express:1
    restart: unless-stopped
    init: true
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
    networks:
      - devstack
    profiles:
      - dev

  mailpit:
    image: axllent/mailpit:v1.24
    restart: unless-stopped
    init: true
    volumes:
      - ./smtp-ssl:/smtp-ssl:ro
    ports:
      - 127.0.0.1:1025:1025
      - 127.0.0.1:8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_SMTP_TLS_CERT: /smtp-ssl/localhost.crt
      MP_SMTP_TLS_KEY: /smtp-ssl/localhost.key
    profiles:
      - dev
      - test

  docs:
    image: squidfunk/mkdocs-material:9.6.13
    restart: unless-stopped
    volumes:
      - ../docs:/docs:ro
      - ../Tekst-Web/i18n/help/enUS:/Tekst-Web/i18n/help/enUS:ro
    ports:
      - 127.0.0.1:8091:8000
    profiles:
      - docs

volumes:
  mongo_configdb:
  mongo_db:
  es_data:

networks:
  devstack:
