version: '3.1'

services:

  textrig-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    environment:
      APP_NAME: "TextRig (dev mode)"
      DB_HOST: "mongo"
      DB_PORT: 27017
      DB_USER: "root"
      DB_PASS: "root"

  mongo:
    image: mongo:5.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/