version: "3.9"

services:

  caddy:
    image: "caddy:2.6-alpine"
    volumes:
      - "./:/etc/caddy/:ro"
    network_mode: "host"
    profiles:
      - dev

  mongo:
    image: mongo:5.0.9
    restart: always
    init: true
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - devstack
    profiles:
      - dev
      - test
    command: mongod --setParameter diagnosticDataCollectionEnabled=false

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    init: true
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - devstack
    profiles:
      - dev

  mailpit:
    image: axllent/mailpit:v1.6
    restart: always
    init: true
    volumes:
      - ./smtp-ssl:/smtp-ssl
    ports:
      - 127.0.0.1:1025:1025
      - 127.0.0.1:8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_SMTP_TLS_CERT: /smtp-ssl/localhost.crt
      MP_SMTP_TLS_KEY: /smtp-ssl/localhost.key
    profiles:
      - dev
      - test

volumes:
  mongo_configdb:
  mongo_db:

networks:
  devstack:
