<script setup lang="ts">
import { useRouter } from 'vue-router';
import { useAuthStore, useMessagesStore } from '@/stores';
import { type FormInst, type FormRules, NForm, NFormItem, NInput, NButton, NSpace } from 'naive-ui';
import { ref, onMounted, nextTick } from 'vue';
import { useI18n } from 'vue-i18n';

const auth = useAuthStore();
const messages = useMessagesStore();
const router = useRouter();
const { t } = useI18n({ useScope: 'global' });

const loading = ref(false);

const initialFormModel = () => ({
  email: null,
  password: null,
});

const formModel = ref<Record<string, string | null>>(initialFormModel());
const formRef = ref<FormInst | null>(null);
const firstInputRef = ref<HTMLInputElement | null>(null);

const formRules: FormRules = {
  email: [
    {
      required: true,
      message: t('user.rulesFeedback.emailReq'),
      // trigger: 'blur',
    },
  ],
  password: [
    {
      required: true,
      message: t('user.rulesFeedback.passwordReq'),
      trigger: 'blur',
    },
  ],
};

function resetForm() {
  loading.value = false;
  formModel.value = initialFormModel();
  formRef.value?.restoreValidation();
}

function switchToRegistration() {
  resetForm();
  router.push({ name: 'register' });
}

function loginUser() {
  auth
    .login(formModel.value.email || '', formModel.value.password || '')
    .then((u) => {
      resetForm();
      messages.success(t('general.welcome', { name: u.firstName }));
      if (auth.returnUrl) {
        router.push(auth.returnUrl);
        auth.returnUrl = null;
      } else {
        router.push({ name: 'accountProfile', params: { username: u.username } });
      }
    })
    .catch((e) => {
      /**
       * Unfortunately, the errors returned by the endpoints generated by
       * FastAPI-Users have a weird custom model that we have to handle here...
       */
      if (e.response) {
        const data = e.response.data;
        if (data.detail === 'LOGIN_BAD_CREDENTIALS') {
          messages.error(t('user.errors.badCreds'));
        } else if (data.detail === 'LOGIN_USER_NOT_VERIFIED') {
          messages.error(t('user.errors.notVerified'));
        } else if (e.response.status === 403) {
          messages.error(t('errors.csrf'));
        } else {
          messages.error(t('errors.unexpected'));
        }
      } else {
        messages.error(t('errors.unexpected'));
      }
      loading.value = false;
    });
}

function handleLoginClick() {
  loading.value = true;
  formRef.value
    ?.validate((errors) => {
      !errors && loginUser();
    })
    .catch(() => {
      messages.error(t('errors.followFormRules'));
      loading.value = false;
    });
}

function handleForgotPasswordClick() {
  messages.info('So you forgot your password? This is not implemented, yet!');
}

onMounted(() => {
  nextTick(() => {
    firstInputRef.value?.focus();
  });
});
</script>

<template>
  <div class="form-container">
    <div class="content-block">
      <h2 style="text-align: center">{{ $t('user.heading') }}</h2>
      <n-form
        ref="formRef"
        :model="formModel"
        :rules="formRules"
        label-placement="top"
        label-width="auto"
        require-mark-placement="right-hanging"
      >
        <n-form-item path="email" :label="$t('user.labels.email')">
          <n-input
            v-model:value="formModel.email"
            type="text"
            :placeholder="$t('user.labels.email')"
            @keydown.enter.prevent
            ref="firstInputRef"
          />
        </n-form-item>
        <n-form-item path="password" :label="$t('user.labels.password')">
          <n-input
            v-model:value="formModel.password"
            type="password"
            :placeholder="$t('user.labels.password')"
            @keyup.enter="() => handleLoginClick()"
          />
        </n-form-item>
      </n-form>

      <div style="display: flex; justify-content: flex-end">
        <n-button
          text
          :focusable="false"
          style="margin-bottom: 2rem; font-size: var(--app-ui-font-size-mini)"
          @click="handleForgotPasswordClick"
        >
          {{ $t('user.forgotPassword') }}
        </n-button>
      </div>

      <n-space vertical :size="12">
        <n-button
          block
          type="primary"
          @click="handleLoginClick"
          :loading="loading"
          :disabled="loading"
        >
          {{ $t('user.login') }}
        </n-button>
        <n-button secondary block @click="switchToRegistration">
          {{ $t('user.switchToRegister') }}
        </n-button>
      </n-space>
    </div>
  </div>
</template>
