<script setup lang="ts">
import router from '@/router';
import { useAuthStore, useMessagesStore } from '@/stores';
import {
  type FormInst,
  type FormValidationError,
  type FormRules,
  NForm,
  NFormItem,
  NInput,
  NButton,
  NCard,
  NSpace,
} from 'naive-ui';
import { ref } from 'vue';
import { i18n } from '@/i18n';

const t = i18n.global.t;
const auth = useAuthStore();
const messages = useMessagesStore();

const loading = ref(false);

const initialFormModel = () => ({
  email: null,
  password: null,
});

const formModel = ref<Record<string, string | null>>(initialFormModel());
const formRef = ref<FormInst | null>(null);

const formRules: FormRules = {
  email: [
    {
      required: true,
      message: t('login.rulesFeedback.emailReq'),
      trigger: 'blur',
    },
  ],
  password: [
    {
      required: true,
      message: t('login.rulesFeedback.passwordReq'),
      trigger: 'blur',
    },
  ],
};

function resetForm() {
  loading.value = false;
  formModel.value = initialFormModel();
  formRef.value?.restoreValidation();
}

function switchToRegistration() {
  resetForm();
  router.push('/register');
}

function loginUser() {
  auth
    .login(formModel.value.email || '', formModel.value.password || '')
    .then((u) => {
      resetForm();
      messages.success(t('general.welcome', { name: u.firstName }));
      router.push('/account');
    })
    .catch((e) => {
      /**
       * Unfortunately, the errors returned by the endpoints generated by
       * FastAPI-Users have a weird custom model that we have to handle here...
       */
      if (e.response) {
        const data = e.response.data;
        if (data.detail === 'LOGIN_BAD_CREDENTIALS') {
          messages.error(t('login.errors.badCreds'));
        } else if (data.detail === 'LOGIN_USER_NOT_VERIFIED') {
          messages.error(t('login.errors.notVerified'));
        }
      } else {
        messages.error(t('errors.unexpected'));
      }
      loading.value = false;
    });
}

function handleLoginClick() {
  loading.value = true;
  formRef.value
    ?.validate((errors: Array<FormValidationError> | undefined) => {
      !errors && loginUser();
    })
    .catch(() => {
      messages.error(t('errors.followFormRules'));
      loading.value = false;
    });
}

function handleForgotPasswordClick() {
  messages.info('So you forgot your password? This is not implemented, yet!');
}
</script>

<template>
  <h1 style="text-align: center">{{ $t('login.heading') }}</h1>
  <n-card
    embedded
    style="width: 600px; max-width: 100%; margin: 1rem auto"
    size="huge"
    role="dialog"
    aria-modal="true"
  >
    <n-form
      ref="formRef"
      :model="formModel"
      :rules="formRules"
      size="large"
      label-placement="top"
      label-width="auto"
      require-mark-placement="right-hanging"
    >
      <n-form-item path="email" :label="$t('login.labels.email')">
        <n-input
          v-model:value="formModel.email"
          type="text"
          :placeholder="$t('login.labels.email')"
          @keydown.enter.prevent
        />
      </n-form-item>
      <n-form-item path="password" :label="$t('login.labels.password')">
        <n-input
          v-model:value="formModel.password"
          type="password"
          :placeholder="$t('login.labels.password')"
          @keyup.enter="() => handleLoginClick()"
        />
      </n-form-item>
    </n-form>

    <div style="display: flex; justify-content: flex-end">
      <n-button
        text
        :focusable="false"
        style="margin-bottom: 2rem; margin-top: -12px; font-size: 0.85rem"
        @click="handleForgotPasswordClick"
      >
        {{ $t('login.forgotPassword') }}
      </n-button>
    </div>

    <n-space vertical :size="12">
      <n-button
        block
        size="large"
        type="primary"
        @click="handleLoginClick"
        :loading="loading"
        :disabled="loading"
      >
        {{ $t('login.login') }}
      </n-button>
      <n-button secondary block size="large" @click="switchToRegistration">
        {{ $t('login.switchToRegister') }}
      </n-button>
    </n-space>
  </n-card>
</template>
