<script setup lang="ts">
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { NButton, NSpace, type FormInst } from 'naive-ui';
import type { UserCreate } from '@/openapi';
import { useApi } from '@/api';
import { useMessages } from '@/messages';
import { usePlatformData } from '@/platformData';
import { useAuthStore } from '@/stores';
import UserForm from '@/forms/UserForm.vue';
import router from '@/router';

const auth = useAuthStore();
const { message } = useMessages();
const { pfData } = usePlatformData();
const { authApi } = useApi();
const { t } = useI18n({ useScope: 'global' });

const userForm = ref<typeof UserForm>();
const formRef = computed<FormInst | null>(() => userForm.value?.formRef);
const formModel = computed<Record<string, string | null>>(() => userForm.value?.formModel);
const loading = ref(false);

function registerUser() {
  authApi
    .registerRegister({ userCreate: formModel.value as unknown as UserCreate })
    .then(() => {
      if (!pfData.value?.security?.usersActiveByDefault) {
        message.success(`${t('register.success')} ${t('register.activationNeededHint')}`, 20);
        resetForm();
        router.push({ name: 'home' });
      } else {
        message.success(`${t('register.success')} ${t('register.activationNotNeededHint')}`, 10);
        switchToLogin();
      }
    })
    .catch((e) => {
      /**
       * Unfortunately, the errors returned by the endpoints generated by
       * FastAPI-Users have a weird custom model that we have to handle here...
       */
      if (e.response) {
        const data = e.response.data;
        if (data.detail === 'REGISTER_USER_ALREADY_EXISTS') {
          message.error(t('register.errors.emailAlreadyRegistered'));
        } else if (data.detail === 'REGISTER_USERNAME_ALREADY_EXISTS') {
          message.error(t('register.errors.usernameAlreadyRegistered'));
        } else if (data.detail.code === 'REGISTER_INVALID_PASSWORD') {
          message.error(t('register.errors.weakPassword'));
        } else if (e.response.status === 403) {
          message.error(t('errors.csrf'));
        } else {
          message.error(t('errors.unexpected'));
        }
      }
      loading.value = false;
    });
}

function handleRegisterClick(e: MouseEvent | null = null) {
  e && e.preventDefault();
  loading.value = true;
  formRef.value
    ?.validate((errors) => {
      !errors && registerUser();
    })
    .catch(() => {
      message.error(t('errors.followFormRules'));
      loading.value = false;
    });
}

function resetForm() {
  loading.value = false;
  userForm.value?.reset();
}

function switchToLogin() {
  auth.showLoginModal(undefined, { name: 'accountProfile' });
  resetForm();
}
</script>

<template>
  <h2 style="text-align: center">{{ $t('register.heading') }}</h2>
  <div class="form-container">
    <div class="content-block">
      <UserForm ref="userForm" @submit="handleRegisterClick" />
      <n-space vertical :size="12" style="margin-top: 1rem">
        <n-button
          block
          type="primary"
          @click="handleRegisterClick"
          :loading="loading"
          :disabled="loading"
        >
          {{ $t('register.register') }}
        </n-button>
        <n-button secondary block @click="switchToLogin">
          {{ $t('register.switchToLogin') }}
        </n-button>
      </n-space>
    </div>
  </div>
</template>
