<script setup lang="ts">
import router from '@/router';
import { useAuthStore, useStateStore, useMessagesStore } from '@/stores';
import {
  type FormInst,
  type FormValidationError,
  type FormRules,
  NForm,
  NFormItem,
  NInput,
  NButton,
  NCard,
  NModal,
} from 'naive-ui';
import { ref } from 'vue';

const state = useStateStore();
const auth = useAuthStore();
const messages = useMessagesStore();

const loading = ref(false);

const initialFormModel = () => ({
  email: null,
  password: null,
});

const formModel = ref<Record<string, string | null>>(initialFormModel());
const formRef = ref<FormInst | null>(null);
const formLabelsLeft = window.innerWidth > 600;

const rules: FormRules = {
  email: [
    {
      required: true,
      message: 'Email is required',
      trigger: 'blur',
    },
  ],
  password: [
    {
      required: true,
      message: 'Password is required',
      trigger: 'blur',
    },
  ],
};

function closeLogin() {
  formModel.value = initialFormModel();
  formRef.value?.restoreValidation();
  state.showLogin = false;
}

function switchToRegistration() {
  closeLogin();
  state.openRegistration();
}

function loginUser() {
  auth
    .login(formModel.value.email || '', formModel.value.password || '')
    .then(() => router.push('/account'))
    .catch(async (e) => {
      /**
       * Unfortunately, the errors returned by the endpoints generated by
       * FastAPI-Users have a weird custom model that we have to handle here...
       */
      const status = e.response.status;
      const r = await e.response.json();

      if (status == 400) {
        if (r.detail === 'LOGIN_BAD_CREDENTIALS') {
          messages.error('Incorrect email or password');
        } else if (r.detail === 'LOGIN_USER_NOT_VERIFIED') {
          messages.error(
            'Your account is not yet verified. We re-sent your verification link via email.'
          );
        }
      } else {
        messages.error('An unexpected error occurred. This should not happen.');
      }
      loading.value = false;
    });
}

function handleLoginClick(e: MouseEvent) {
  e.preventDefault();
  loading.value = true;
  formRef.value
    ?.validate((errors: Array<FormValidationError> | undefined) => {
      !errors && loginUser();
    })
    .catch(() => {
      messages.error('Please correct your input according to the form rules.');
      loading.value = false;
    });
}
</script>

<template>
  <n-modal
    v-model:show="state.showLogin"
    :on-close="closeLogin"
    :on-esc="closeLogin"
    :on-mask-click="closeLogin"
    :on-update:show="() => null"
  >
    <n-card
      style="width: 720px"
      title="Log in to your account"
      :bordered="false"
      :segmented="{ content: 'soft', footer: 'soft' }"
      size="huge"
      role="dialog"
      aria-modal="true"
      :on-close="closeLogin"
      closable
    >
      <n-form
        ref="formRef"
        :model="formModel"
        :rules="rules"
        size="large"
        :label-placement="formLabelsLeft ? 'left' : 'top'"
        label-width="auto"
        require-mark-placement="right-hanging"
      >
        <n-form-item path="email" label="Email">
          <n-input
            v-model:value="formModel.email"
            type="text"
            placeholder="..."
            @keydown.enter.prevent
          />
        </n-form-item>
        <n-form-item path="password" label="Password">
          <n-input v-model:value="formModel.password" type="password" placeholder="..." />
        </n-form-item>
      </n-form>

      <template #footer>
        <div style="display: flex; justify-content: flex-end; gap: 12px">
          <n-button
            quaternary
            type="primary"
            size="large"
            :focusable="false"
            tabindex="-1"
            @click="switchToRegistration"
          >
            Register new account
          </n-button>
          <n-button
            size="large"
            type="primary"
            @click="handleLoginClick"
            :loading="loading"
            :disabled="loading"
          >
            Login
          </n-button>
        </div>
      </template>
    </n-card>
  </n-modal>
</template>
