<script setup lang="ts">
import { ref } from 'vue';
import { useMessagesStore, useStateStore } from '@/stores';
import {
  type FormInst,
  type FormItemInst,
  type FormItemRule,
  type FormValidationError,
  type FormRules,
  NForm,
  NFormItem,
  NInput,
  NButton,
  NCard,
  NModal,
} from 'naive-ui';
import { AuthApi, type UserCreate } from '@/openapi';

const state = useStateStore();
const messages = useMessagesStore();
const authApi = new AuthApi();

const initialFormModel = () => ({
  email: null,
  password: null,
  passwordRepeat: null,
  firstName: null,
  lastName: null,
});

const formModel = ref<Record<string, string | null>>(initialFormModel());

const formRef = ref<FormInst | null>(null);
const rPasswordFormItemRef = ref<FormItemInst | null>(null);
const loading = ref(false);
const formLabelsLeft = window.innerWidth > 600;

function validateEmail(rule: FormItemRule, value: string): boolean {
  return /^.+@.+\.\w+$/.test(value);
}

function validatePasswordLength(rule: FormItemRule, value: string): boolean {
  return !!value && value.length >= 8;
}

function validatePasswordChars(rule: FormItemRule, value: string): boolean {
  return !!value && /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/.test(value);
}

function validatePasswordsMatch(rule: FormItemRule, value: string): boolean {
  return !!value && !!formModel.value.password && value === formModel.value.password;
}

const formRules: FormRules = {
  email: [
    {
      required: true,
      message: 'Email is required',
      trigger: 'blur',
    },
    {
      validator: validateEmail,
      message: 'Email is too obviously invalid',
      trigger: 'blur',
    },
  ],
  password: [
    {
      required: true,
      message: 'Password is required',
      trigger: 'blur',
    },
    {
      validator: validatePasswordLength,
      message: 'Password must be at least 8 characters long',
      trigger: ['input', 'blur'],
    },
    {
      validator: validatePasswordChars,
      message: 'Password must contain at least one of each: a-z, A-Z and 0-9',
      trigger: ['input', 'blur'],
    },
  ],
  passwordRepeat: [
    {
      required: true,
      message: 'Password repetition is required',
      trigger: 'blur',
    },
    {
      validator: validatePasswordsMatch,
      message: "Passwords don't match",
      trigger: ['input', 'blur', 'password-input'],
    },
  ],
  firstName: [
    {
      required: true,
      message: 'First name is required',
      trigger: 'blur',
    },
  ],
  lastName: [
    {
      required: true,
      message: 'Last name is required',
      trigger: 'blur',
    },
  ],
};

function handlePasswordInput() {
  if (formModel.value.reenteredPassword) {
    rPasswordFormItemRef.value?.validate({ trigger: 'password-input' });
  }
}

function registerUser() {
  authApi
    .registerRegister({ userCreate: formModel.value as unknown as UserCreate })
    .then(() => {
      messages.success('Successfully registered. You can now log in.');
      switchToLogin();
    })
    .catch((e) => {
      /**
       * Unfortunately, the errors returned by the endpoints generated by
       * FastAPI-Users have a weird custom model that we have to handle here...
       */
      if (e.response) {
        const data = e.response.data;
        if (data.detail && data.detail === 'REGISTER_USER_ALREADY_EXISTS') {
          messages.error('This email address is already registered.');
        } else if (data.detail?.code === 'REGISTER_INVALID_PASSWORD') {
          messages.error("Your password doesn't meet the security requirements.");
        } else {
          messages.error('An unexpected error occurred. This should not happen.');
        }
      }
      loading.value = false;
    });
}

function handleRegisterClick(e: MouseEvent | null = null) {
  e && e.preventDefault();
  loading.value = true;
  formRef.value
    ?.validate((errors: Array<FormValidationError> | undefined) => {
      !errors && registerUser();
    })
    .catch(() => {
      messages.error('Please correct your input according to the form rules.');
      loading.value = false;
    });
}

function closeRegistration() {
  loading.value = false;
  formModel.value = initialFormModel();
  formRef.value?.restoreValidation();
  state.showRegistration = false;
}

function switchToLogin() {
  closeRegistration();
  state.openLogin();
}
</script>

<template>
  <n-modal
    v-model:show="state.showRegistration"
    :on-close="closeRegistration"
    :on-esc="closeRegistration"
    :on-mask-click="closeRegistration"
    :on-update:show="() => null"
  >
    <n-card
      embedded
      style="width: 720px"
      title="Register new account"
      :bordered="false"
      size="huge"
      :segmented="{ content: 'soft', footer: 'soft' }"
      role="dialog"
      aria-modal="true"
      :on-close="closeRegistration"
      closable
    >
      <n-form
        ref="formRef"
        :model="formModel"
        :rules="formRules"
        size="large"
        :label-placement="formLabelsLeft ? 'left' : 'top'"
        label-width="auto"
        require-mark-placement="right-hanging"
      >
        <n-form-item path="email" label="Email">
          <n-input
            v-model:value="formModel.email"
            type="text"
            placeholder="..."
            @keydown.enter.prevent
          />
        </n-form-item>
        <n-form-item path="password" label="Password">
          <n-input
            v-model:value="formModel.password"
            type="password"
            placeholder="..."
            @input="handlePasswordInput"
            @keydown.enter.prevent
          />
        </n-form-item>
        <n-form-item ref="rPasswordFormItemRef" first path="passwordRepeat" label="Repeat Password">
          <n-input
            v-model:value="formModel.passwordRepeat"
            :disabled="!formModel.password"
            type="password"
            placeholder="..."
            @keydown.enter.prevent
          />
        </n-form-item>
        <n-form-item path="firstName" label="First Name">
          <n-input
            v-model:value="formModel.firstName"
            type="text"
            placeholder="..."
            @keydown.enter.prevent
          />
        </n-form-item>
        <n-form-item path="lastName" label="Last Name">
          <n-input
            v-model:value="formModel.lastName"
            type="text"
            placeholder="..."
            @keyup.enter="() => handleRegisterClick()"
          />
        </n-form-item>
      </n-form>

      <template #footer>
        <div style="display: flex; justify-content: flex-end; gap: 12px">
          <n-button
            quaternary
            type="primary"
            size="large"
            :focusable="false"
            tabindex="-1"
            @click="switchToLogin"
          >
            Log in to existing account
          </n-button>
          <n-button
            type="primary"
            @click="handleRegisterClick"
            :loading="loading"
            :disabled="loading"
            size="large"
          >
            Register
          </n-button>
        </div>
      </template>
    </n-card>
  </n-modal>
</template>
