# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: Print this very list of available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Generate script via bashly (uses Docker)
    cmds:
      - docker run --rm -it --user $(id -u):$(id -g) --volume "$PWD:/app" dannyben/bashly generate
