site_name: Tekst
docs_dir: content
repo_url: https://github.com/VedaWebProject/Tekst
repo_name: VedaWebProject/Tekst
site_description: A tool for creating open collaborative text research platforms

nav:
  - What is Tekst?: index.md
  - Concepts: concepts.md
  - Setup:
    - setup/installation.md
    - setup/configuration.md
    - setup/customization.md
  - User Guide:
    - usage/resources.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["./generated/help/"]
      check_paths: true
  - pymdownx.superfences

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
