site_name: Tekst
docs_dir: content
repo_url: https://github.com/VedaWebProject/Tekst
repo_name: VedaWebProject/Tekst
site_description: A tool for creating open collaborative text research platforms

nav:
  - 'index.md'
  - 'concepts.md'
  - 'setup.md'
  - Usage:
    - 'Data Layers': 'usage/data-layers.md'

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["./generated/help/"]
      check_paths: true
  - pymdownx.superfences

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
