site_name: Tekst
docs_dir: content
repo_url: https://github.com/VedaWebProject/Tekst
repo_name: VedaWebProject/Tekst
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: default
    primary: teal
    accent: teal
