/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/admin": {
    /** Hello admin */
    get: operations["helloAdmin"];
  };
  "/layers/plaintext/{id}": {
    /**
     * Get layer 
     * @description Returns the data for a PlainText data layer
     */
    get: operations["getPlaintextLayer"];
    /**
     * Update layer 
     * @description Updates the data for a PlainText data layer
     */
    patch: operations["updatePlaintextLayer"];
  };
  "/layers/plaintext": {
    /**
     * Create layer 
     * @description Creates a PlainText data layer definition
     */
    post: operations["createPlaintextLayer"];
  };
  "/layers": {
    /**
     * Get layers 
     * @description Returns a list of all data layers matching the given criteria.
     * 
     * As the resulting list of data layers may contain layers of different types, the
     * returned layer objects are reduced to the common layer properties and do not
     * contain layer type-specific data.
     */
    get: operations["getLayers"];
  };
  "/layers/{id}": {
    /** Get layer */
    get: operations["getLayer"];
  };
  "/nodes": {
    /** Get nodes */
    get: operations["getNodes"];
    /** Create node */
    post: operations["createNode"];
  };
  "/nodes/{id}": {
    /** Update node */
    patch: operations["updateNode"];
  };
  "/nodes/{id}/children": {
    /** Get children */
    get: operations["getChildren"];
  };
  "/nodes/{id}/next": {
    /** Get next */
    get: operations["getNext"];
  };
  "/texts": {
    /** Get all texts */
    get: operations["getAllTexts"];
    /** Create text */
    post: operations["createText"];
  };
  "/texts/import": {
    /** Import text */
    post: operations["importText"];
  };
  "/texts/{id}": {
    /** Get text */
    get: operations["getText"];
    /** Update text */
    patch: operations["updateText"];
  };
  "/uidata": {
    /**
     * Uidata 
     * @description Returns data the client needs to initialize
     */
    get: operations["uidata"];
  };
  "/uidata/platform": {
    /**
     * Uidata platform 
     * @description Returns platform metadata, possibly customized for this platform instance.
     */
    get: operations["uidataPlatform"];
  };
  "/uidata/i18n": {
    /**
     * Uidata i18n 
     * @description Returns server-managed translations.
     */
    get: operations["uidataI18n"];
  };
  "/units/plaintext/{id}": {
    /**
     * Get unit 
     * @description Returns the data for a PlainText data layer unit
     */
    get: operations["getPlaintextUnit"];
    /**
     * Update unit 
     * @description Updates the data for a PlainText data layer unit
     */
    patch: operations["updatePlaintextUnit"];
  };
  "/units/plaintext": {
    /**
     * Create unit 
     * @description Creates a PlainText data layer unit
     */
    post: operations["createPlaintextUnit"];
  };
  "/auth/cookie/login": {
    /** Login */
    post: operations["auth:cookie.login"];
  };
  "/auth/cookie/logout": {
    /** Logout */
    post: operations["auth:cookie.logout"];
  };
  "/auth/jwt/login": {
    /** Login */
    post: operations["auth:jwt.login"];
  };
  "/auth/jwt/logout": {
    /** Logout */
    post: operations["auth:jwt.logout"];
  };
  "/auth/register": {
    /** Register */
    post: operations["register:register"];
  };
  "/auth/request-verify-token": {
    /** Request verify token */
    post: operations["verify:requestToken"];
  };
  "/auth/verify": {
    /** Verify */
    post: operations["verify:verify"];
  };
  "/auth/forgot-password": {
    /** Forgot password */
    post: operations["reset:forgotPassword"];
  };
  "/auth/reset-password": {
    /** Reset password */
    post: operations["reset:resetPassword"];
  };
  "/users/me": {
    /** Me */
    get: operations["users:currentUser"];
    /** Update me */
    patch: operations["users:patchCurrentUser"];
  };
  "/users/{id}": {
    /** Get user */
    get: operations["users:user"];
    /** Delete user */
    delete: operations["users:deleteUser"];
    /** Update user */
    patch: operations["users:patchUser"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** BearerResponse */
    BearerResponse: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
    };
    /** Body_auth_cookie_login_auth_cookie_login_post */
    Body_auth_cookie_login_auth_cookie_login_post: {
      /** Grant Type */
      grant_type?: string;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope 
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string;
      /** Client Secret */
      client_secret?: string;
    };
    /** Body_auth_jwt_login_auth_jwt_login_post */
    Body_auth_jwt_login_auth_jwt_login_post: {
      /** Grant Type */
      grant_type?: string;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope 
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string;
      /** Client Secret */
      client_secret?: string;
    };
    /** Body_import_text_texts_import_post */
    Body_import_text_texts_import_post: {
      /**
       * File 
       * Format: binary
       */
      file: string;
    };
    /** Body_reset_forgot_password_auth_forgot_password_post */
    Body_reset_forgot_password_auth_forgot_password_post: {
      /**
       * Email 
       * Format: email
       */
      email: string;
    };
    /** Body_reset_reset_password_auth_reset_password_post */
    Body_reset_reset_password_auth_reset_password_post: {
      /** Token */
      token: string;
      /** Password */
      password: string;
    };
    /** Body_verify_request_token_auth_request_verify_token_post */
    Body_verify_request_token_auth_request_verify_token_post: {
      /**
       * Email 
       * Format: email
       */
      email: string;
    };
    /** Body_verify_verify_auth_verify_post */
    Body_verify_verify_auth_verify_post: {
      /** Token */
      token: string;
    };
    /** DeepLLinksConfig */
    DeepLLinksConfig: {
      /**
       * Enabled 
       * @description Enable/disable quick translation links to DeepL 
       * @default false
       */
      enabled?: boolean;
      /**
       * Source Language 
       * @description Source language 
       * @enum {string}
       */
      source_language?: "BG" | "CS" | "DA" | "DE" | "EL" | "EN" | "ES" | "ET" | "FI" | "FR" | "HU" | "ID" | "IT" | "JA" | "LT" | "LV" | "NL" | "PL" | "PT" | "RO" | "RU" | "SK" | "SL" | "SV" | "TR" | "UK" | "ZH";
      /**
       * Languages 
       * @description Target languages to display links for 
       * @default [
       *   "EN",
       *   "DE"
       * ]
       */
      languages?: ("BG" | "CS" | "DA" | "DE" | "EL" | "EN" | "ES" | "ET" | "FI" | "FR" | "HU" | "ID" | "IT" | "JA" | "LT" | "LV" | "NL" | "PL" | "PT" | "RO" | "RU" | "SK" | "SL" | "SV" | "TR" | "UK" | "ZH")[];
    };
    /** ErrorModel */
    ErrorModel: {
      /** Detail */
      detail: string | ({
        [key: string]: string | undefined;
      });
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: (components["schemas"]["ValidationError"])[];
    };
    /**
     * LayerBaseRead 
     * @description A data layer describing a set of data on a text
     */
    LayerBaseRead: {
      /** Id */
      id: string;
      /**
       * Title 
       * @description Title of this layer
       */
      title: string;
      /**
       * Description 
       * @description Short, one-line description of this data layer
       */
      description?: string;
      /**
       * Textid 
       * @description ID of the text this layer belongs to
       */
      textId?: string;
      /**
       * Level 
       * @description Text level this layer belongs to
       */
      level: number;
      /**
       * Layertype 
       * @description A string identifying one of the available layer types
       */
      layerType: string;
      /**
       * Public 
       * @description Publication status of this layer 
       * @default false
       */
      public?: boolean;
      /**
       * Meta 
       * @description Arbitrary metadata
       */
      meta?: {
        [key: string]: (string | number | boolean | number) | undefined;
      };
    };
    /**
     * NodeCreate 
     * @description A node in a text structure (e.g. chapter, paragraph, ...)
     */
    NodeCreate: {
      /**
       * Textid 
       * @description ID of the text this node belongs to
       */
      textId: string;
      /**
       * Parentid 
       * @description ID of parent node
       */
      parentId?: string;
      /**
       * Level 
       * @description Index of structure level this node is on
       */
      level: number;
      /**
       * Index 
       * @description Position among all text nodes on this level
       */
      index: number;
      /**
       * Label 
       * @description Label for identifying this text node
       */
      label: string;
      /**
       * Meta 
       * @description Arbitrary metadata
       */
      meta?: {
        [key: string]: (string | number | boolean | number) | undefined;
      };
    };
    /**
     * NodeRead 
     * @description A node in a text structure (e.g. chapter, paragraph, ...)
     */
    NodeRead: {
      /** Id */
      id: string;
      /**
       * Textid 
       * @description ID of the text this node belongs to
       */
      textId: string;
      /**
       * Parentid 
       * @description ID of parent node
       */
      parentId?: string;
      /**
       * Level 
       * @description Index of structure level this node is on
       */
      level: number;
      /**
       * Index 
       * @description Position among all text nodes on this level
       */
      index: number;
      /**
       * Label 
       * @description Label for identifying this text node
       */
      label: string;
      /**
       * Meta 
       * @description Arbitrary metadata
       */
      meta?: {
        [key: string]: (string | number | boolean | number) | undefined;
      };
    };
    /**
     * NodeUpdate 
     * @description A node in a text structure (e.g. chapter, paragraph, ...)
     */
    NodeUpdate: {
      /** Textid */
      textId?: string;
      /** Parentid */
      parentId?: string;
      /** Level */
      level?: number;
      /** Index */
      index?: number;
      /** Label */
      label?: string;
      /** Meta */
      meta?: {
        [key: string]: (string | number | boolean | number) | undefined;
      };
    };
    /** PlainTextLayerConfig */
    PlainTextLayerConfig: {
      /**
       * Deepl Links 
       * @default {
       *   "enabled": false,
       *   "languages": [
       *     "EN",
       *     "DE"
       *   ]
       * }
       */
      deepl_links?: components["schemas"]["DeepLLinksConfig"];
    };
    /**
     * PlainTextLayerCreate 
     * @description A data layer describing a set of data on a text
     */
    PlainTextLayerCreate: {
      /**
       * Title 
       * @description Title of this layer
       */
      title: string;
      /**
       * Description 
       * @description Short, one-line description of this data layer
       */
      description?: string;
      /**
       * Textid 
       * @description ID of the text this layer belongs to
       */
      textId?: string;
      /**
       * Level 
       * @description Text level this layer belongs to
       */
      level: number;
      /**
       * Layertype 
       * @description A string identifying one of the available layer types
       */
      layerType: string;
      /**
       * Public 
       * @description Publication status of this layer 
       * @default false
       */
      public?: boolean;
      /**
       * Meta 
       * @description Arbitrary metadata
       */
      meta?: {
        [key: string]: (string | number | boolean | number) | undefined;
      };
      /**
       * Config 
       * @default {
       *   "deepl_links": {
       *     "enabled": false,
       *     "languages": [
       *       "EN",
       *       "DE"
       *     ]
       *   }
       * }
       */
      config?: components["schemas"]["PlainTextLayerConfig"];
    };
    /**
     * PlainTextLayerRead 
     * @description A data layer describing a set of data on a text
     */
    PlainTextLayerRead: {
      /** Id */
      id: string;
      /**
       * Title 
       * @description Title of this layer
       */
      title: string;
      /**
       * Description 
       * @description Short, one-line description of this data layer
       */
      description?: string;
      /**
       * Textid 
       * @description ID of the text this layer belongs to
       */
      textId?: string;
      /**
       * Level 
       * @description Text level this layer belongs to
       */
      level: number;
      /**
       * Layertype 
       * @description A string identifying one of the available layer types
       */
      layerType: string;
      /**
       * Public 
       * @description Publication status of this layer 
       * @default false
       */
      public?: boolean;
      /**
       * Meta 
       * @description Arbitrary metadata
       */
      meta?: {
        [key: string]: (string | number | boolean | number) | undefined;
      };
      /**
       * Config 
       * @default {
       *   "deepl_links": {
       *     "enabled": false,
       *     "languages": [
       *       "EN",
       *       "DE"
       *     ]
       *   }
       * }
       */
      config?: components["schemas"]["PlainTextLayerConfig"];
    };
    /**
     * PlainTextLayerUpdate 
     * @description A data layer describing a set of data on a text
     */
    PlainTextLayerUpdate: {
      /** Title */
      title?: string;
      /** Description */
      description?: string;
      /** Textid */
      textId?: string;
      /** Level */
      level?: number;
      /** Layertype */
      layerType?: string;
      /** Public */
      public?: boolean;
      /** Meta */
      meta?: {
        [key: string]: (string | number | boolean | number) | undefined;
      };
      config?: components["schemas"]["PlainTextLayerConfig"];
    };
    /**
     * PlainTextUnitCreate 
     * @description A unit of a plaintext data layer
     */
    PlainTextUnitCreate: {
      /**
       * Layerid 
       * @description Data layer ID
       */
      layerId: string;
      /**
       * Nodeid 
       * @description Parent text node ID
       */
      nodeId: string;
      /**
       * Meta 
       * @description Arbitrary metadata on this layer unit
       */
      meta?: {
        [key: string]: (string | number | boolean | number) | undefined;
      };
      /**
       * Text 
       * @description Text content of the plaintext unit
       */
      text?: string;
    };
    /**
     * PlainTextUnitRead 
     * @description A unit of a plaintext data layer
     */
    PlainTextUnitRead: {
      /** Id */
      id: string;
      /**
       * Layerid 
       * @description Data layer ID
       */
      layerId: string;
      /**
       * Nodeid 
       * @description Parent text node ID
       */
      nodeId: string;
      /**
       * Meta 
       * @description Arbitrary metadata on this layer unit
       */
      meta?: {
        [key: string]: (string | number | boolean | number) | undefined;
      };
      /**
       * Text 
       * @description Text content of the plaintext unit
       */
      text?: string;
    };
    /**
     * PlainTextUnitUpdate 
     * @description A unit of a plaintext data layer
     */
    PlainTextUnitUpdate: {
      /** Layerid */
      layerId?: string;
      /** Nodeid */
      nodeId?: string;
      /** Meta */
      meta?: {
        [key: string]: (string | number | boolean | number) | undefined;
      };
      /** Text */
      text?: string;
    };
    /**
     * TextCreate 
     * @description A text represented in TextRig
     */
    TextCreate: {
      /**
       * Title 
       * @description Title of this text
       */
      title: string;
      /**
       * Slug 
       * @description A short identifier string for use in URLs and internal operations
       */
      slug: string;
      /**
       * Subtitle 
       * @description Subtitle of this text
       */
      subtitle?: string;
      /** Levels */
      levels: (string)[];
      /**
       * Locdelim 
       * @description Delimiter for displaying text locations 
       * @default ,
       */
      locDelim?: string;
    };
    /**
     * TextRead 
     * @description A text represented in TextRig
     */
    TextRead: {
      /** Id */
      id: string;
      /**
       * Title 
       * @description Title of this text
       */
      title: string;
      /**
       * Slug 
       * @description A short identifier string for use in URLs and internal operations
       */
      slug: string;
      /**
       * Subtitle 
       * @description Subtitle of this text
       */
      subtitle?: string;
      /** Levels */
      levels: (string)[];
      /**
       * Locdelim 
       * @description Delimiter for displaying text locations 
       * @default ,
       */
      locDelim?: string;
    };
    /**
     * TextUpdate 
     * @description A text represented in TextRig
     */
    TextUpdate: {
      /** Title */
      title?: string;
      /** Slug */
      slug?: string;
      /** Subtitle */
      subtitle?: string;
      /** Levels */
      levels?: (string)[];
      /** Locdelim */
      locDelim?: string;
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Email 
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /**
       * Is Active 
       * @default true
       */
      is_active?: boolean;
      /**
       * Is Superuser 
       * @default false
       */
      is_superuser?: boolean;
      /**
       * Is Verified 
       * @default true
       */
      is_verified?: boolean;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
    };
    /**
     * UserRead 
     * @description Base User model.
     */
    UserRead: {
      /** Id */
      id: string;
      /**
       * Email 
       * Format: email
       */
      email: string;
      /**
       * Is Active 
       * @default true
       */
      is_active?: boolean;
      /**
       * Is Superuser 
       * @default false
       */
      is_superuser?: boolean;
      /**
       * Is Verified 
       * @default true
       */
      is_verified?: boolean;
      /** First Name */
      first_name: string;
      /** Last Name */
      last_name: string;
    };
    /** UserUpdate */
    UserUpdate: {
      /** Password */
      password?: string;
      /**
       * Email 
       * Format: email
       */
      email?: string;
      /**
       * Is Active 
       * @default true
       */
      is_active?: boolean;
      /** Is Superuser */
      is_superuser?: boolean;
      /**
       * Is Verified 
       * @default true
       */
      is_verified?: boolean;
      /** First Name */
      first_name?: string;
      /** Last Name */
      last_name?: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  helloAdmin: {
    /** Hello admin */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
    };
  };
  getPlaintextLayer: {
    /**
     * Get layer 
     * @description Returns the data for a PlainText data layer
     */
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlainTextLayerRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  updatePlaintextLayer: {
    /**
     * Update layer 
     * @description Updates the data for a PlainText data layer
     */
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlainTextLayerUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlainTextLayerRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  createPlaintextLayer: {
    /**
     * Create layer 
     * @description Creates a PlainText data layer definition
     */
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlainTextLayerCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PlainTextLayerRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getLayers: {
    /**
     * Get layers 
     * @description Returns a list of all data layers matching the given criteria.
     * 
     * As the resulting list of data layers may contain layers of different types, the
     * returned layer objects are reduced to the common layer properties and do not
     * contain layer type-specific data.
     */
    parameters: {
      query: {
        textId: string;
        level?: number;
        layerType?: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (components["schemas"]["LayerBaseRead"])[];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getLayer: {
    /** Get layer */
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LayerBaseRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getNodes: {
    /** Get nodes */
    parameters: {
      query: {
        textId: string;
        level?: number;
        index?: number;
        parentId?: string;
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (components["schemas"]["NodeRead"])[];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  createNode: {
    /** Create node */
    requestBody: {
      content: {
        "application/json": components["schemas"]["NodeCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["NodeRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  updateNode: {
    /** Update node */
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NodeUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NodeRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getChildren: {
    /** Get children */
    parameters: {
      query?: {
        limit?: number;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (components["schemas"]["NodeRead"])[];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getNext: {
    /** Get next */
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NodeRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getAllTexts: {
    /** Get all texts */
    parameters?: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (components["schemas"]["TextRead"])[];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  createText: {
    /** Create text */
    requestBody: {
      content: {
        "application/json": components["schemas"]["TextCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TextRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  importText: {
    /** Import text */
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_text_texts_import_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TextRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getText: {
    /** Get text */
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TextRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  updateText: {
    /** Update text */
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TextUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TextRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  uidata: {
    /**
     * Uidata 
     * @description Returns data the client needs to initialize
     */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
    };
  };
  uidataPlatform: {
    /**
     * Uidata platform 
     * @description Returns platform metadata, possibly customized for this platform instance.
     */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string | undefined;
          };
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
    };
  };
  uidataI18n: {
    /**
     * Uidata i18n 
     * @description Returns server-managed translations.
     */
    parameters?: {
      query?: {
        lang?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getPlaintextUnit: {
    /**
     * Get unit 
     * @description Returns the data for a PlainText data layer unit
     */
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlainTextUnitRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  updatePlaintextUnit: {
    /**
     * Update unit 
     * @description Updates the data for a PlainText data layer unit
     */
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlainTextUnitUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlainTextUnitRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  createPlaintextUnit: {
    /**
     * Create unit 
     * @description Creates a PlainText data layer unit
     */
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlainTextUnitCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PlainTextUnitRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "auth:cookie.login": {
    /** Login */
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_auth_cookie_login_auth_cookie_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorModel"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "auth:cookie.logout": {
    /** Logout */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Missing token or inactive user. */
      401: never;
    };
  };
  "auth:jwt.login": {
    /** Login */
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_auth_jwt_login_auth_jwt_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BearerResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorModel"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "auth:jwt.logout": {
    /** Logout */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Missing token or inactive user. */
      401: never;
    };
  };
  "register:register": {
    /** Register */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorModel"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "verify:requestToken": {
    /** Request verify token */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_verify_request_token_auth_request_verify_token_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "verify:verify": {
    /** Verify */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_verify_verify_auth_verify_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorModel"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "reset:forgotPassword": {
    /** Forgot password */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_reset_forgot_password_auth_forgot_password_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "reset:resetPassword": {
    /** Reset password */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_reset_reset_password_auth_reset_password_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorModel"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "users:currentUser": {
    /** Me */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Missing token or inactive user. */
      401: never;
    };
  };
  "users:patchCurrentUser": {
    /** Update me */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorModel"];
        };
      };
      /** @description Missing token or inactive user. */
      401: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "users:user": {
    /** Get user */
    parameters: {
      path: {
        id: Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Invalid Request */
      400: never;
      /** @description Missing token or inactive user. */
      401: never;
      /** @description Not a superuser. */
      403: never;
      /** @description The user does not exist. */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "users:deleteUser": {
    /** Delete user */
    parameters: {
      path: {
        id: Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      204: never;
      /** @description Invalid Request */
      400: never;
      /** @description Missing token or inactive user. */
      401: never;
      /** @description Not a superuser. */
      403: never;
      /** @description The user does not exist. */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  "users:patchUser": {
    /** Update user */
    parameters: {
      path: {
        id: Record<string, never>;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorModel"];
        };
      };
      /** @description Missing token or inactive user. */
      401: never;
      /** @description Not a superuser. */
      403: never;
      /** @description The user does not exist. */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
