version: '3'

tasks:
  default:
    desc: Print this very list of available tasks
    vars:
      TEKST_VERSION:
        sh: task version
    cmds:
      - echo "This is Tekst client {{.TEKST_VERSION}}"
      - task --list
    silent: true

  version:
    desc: Print project version
    cmds:
      - npx -c 'node -p "process.env.npm_package_version"'
    silent: true

  install:
    desc: Install dependencies
    cmds:
      - npm install

  check-updates:
    desc: Check for updates
    cmds:
      - npx npm-check-updates

  update:
    desc: Update dependencies
    cmds:
      - npm update

  dev:
    desc: Run development server
    cmds:
      - npm run start
    silent: true
    ignore_error: true

  format:
    desc: Format code
    cmds:
      - npm run format

  lint:
    desc: Lint code
    cmds:
      - npm run lint

  fix:
    desc: Format and lint code
    cmds:
      - task: lint
      - task: format

  build:
    desc: Build project
    cmds:
      - npm install
      - npm run build

  api-schema:
    cmds:
      - npm run api-schema

  help-texts:
    cmds:
      - npm run help-texts

  pre-commit:
    cmds:
      - task: install
      - task: api-schema
      - task: lint
      - task: format
      - task: build
