# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Print this very list of available tasks
    vars:
      TEKST_VERSION:
        sh: task version
    cmds:
      - echo "This is Tekst client {{.TEKST_VERSION}}"
      - task --list
    silent: true

  version:
    desc: Print project version
    cmds:
      - npx -c 'node -p "process.env.npm_package_version"'
    silent: true

  install:
    desc: Install dependencies
    cmds:
      - npm install

  update:
    desc: Update dependencies
    cmds:
      - npm update

  dev:
    desc: Run development server
    cmds:
      - npm run start
    silent: true
    ignore_error: true

  format:
    desc: Format code
    cmds:
      - npm run format

  lint:
    desc: Lint code
    cmds:
      - npm run lint

  build:
    desc: Build project
    cmds:
      - npm run build

  generate-api-types:
    cmds:
      - cmd: npx openapi-typescript ../Tekst-API/openapi.json -o ./src/api/schema.d.ts
      - cmd: npx eslint ./src/api/schema.d.ts --fix

  help-texts:
    cmds:
      - node scripts/parseHelpTexts.mjs
      - npx eslint src/assets/help/index.ts --fix

  pre-commit:
    cmds:
      - task: generate-api-types
      - task: format
      - task: lint
      - task: build
