name: Test Client Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Tekst-Web/public/**'
      - 'Tekst-Web/scripts/**'
      - 'Tekst-Web/src/**'
      - 'Tekst-Web/package.json'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Tekst-Web/public/**'
      - 'Tekst-Web/scripts/**'
      - 'Tekst-Web/src/**'
      - 'Tekst-Web/package.json'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Tekst-Web

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.17.1
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
        cache: 'npm'
        cache-dependency-path: './Tekst-Web/package-lock.json'
    - run: npm install
    - run: npm run build --if-present
