name: Build and deploy docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "Tekst-Web/i18n/help/enUS/**"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material=="9.*" mkdocs-include-markdown-plugin=="7.*"
      - run: sudo mkdir /includes && sudo cp ../Tekst-Web/i18n/help/enUS/** /includes/
      - run: mkdocs gh-deploy --force
