name: Style Checks

on:
  push:
    branches:
      - development
      - main
    paths:
      - "Tekst-API/tekst/**"
      - "Tekst-API/tests/**"
      - "Tekst-API/pyproject.toml"
      - "Tekst-API/poetry.lock"
      - ".github/workflows/server-style.yml"
  pull_request:
    branches:
      - development
    paths:
      - "Tekst-API/tekst/**"
      - "Tekst-API/tests/**"
      - "Tekst-API/pyproject.toml"
      - "Tekst-API/poetry.lock"
      - ".github/workflows/server-style.yml"
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Tekst-API

    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: "./Tekst-API/poetry.lock"
      - name: Install dependencies
        run: poetry install --sync
      - name: Cancel on setup error
        if: failure()
        uses: andymckay/cancel-action@0.2
      - name: Lint code base
        if: always()
        run: poetry run ruff check . --extend-select N
      - name: Check code formatting
        if: always()
        run: poetry run ruff format . --check
