name: Code Style

on:
  push:
    branches:
      - main
    paths:
      - 'textrig/**'
      - 'tests/**'
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: ${{ !env.ACT && 'poetry' || '' }}
        cache-dependency-path: 'poetry.lock'
    - name: Install dependencies
      run: poetry install --sync
    - name: Cancel on setup error
      if: failure()
      uses: andymckay/cancel-action@0.2
    - name: Check imports order
      if: always()
      run: poetry run isort --check --diff .
    - name: Check code formatting
      if: always()
      run: poetry run black --check --diff .
    - name: Ask linter for its blessing
      if: always()
      run: poetry run flake8 .
