name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'textrig/**'
      - 'tests/**'
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
        cache-dependency-path: 'poetry.lock'
    - name: Install dependencies
      run: poetry install
    - name: Cancel on setup error
      if: failure()
      uses: andymckay/cancel-action@0.2
    - name: Run tests
      if: always()
      run: poetry run coverage run -m pytest
    - name: Read coverage percentage
      run: poetry run coverage json -q -o /dev/stdout | python3 -c "import sys, json; print(round(float(json.load(sys.stdin)['totals']['percent_covered_display']), 1))" | echo "COVERAGE=$(</dev/stdin)" >> $GITHUB_ENV
    - name: Generate coverage badge
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: cd17e3ef6eb05cb28bd038cb409f2ee8
        filename: coverage.json
        label: Coverage
        message: ${{ env.COVERAGE }}%
        valColorRange: ${{ env.COVERAGE }}
        maxColorRange: 100
        minColorRange: 0
