name: TextRig Server Tests

on:
  push:
    branches:
      - main
    paths:
      - 'server/textrig/**'
      - 'server/tests/**'
      - 'server/pyproject.toml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
        cache-dependency-path: 'server/poetry.lock'
    - name: Install dependencies
      run: poetry install
    - name: Cancel on setup error
      if: failure()
      uses: andymckay/cancel-action@0.2
    - name: Check imports order
      if: always()
      run: poetry run isort --check --diff .
    - name: Check code formatting
      if: always()
      run: poetry run black --check --diff .
    - name: Check for code errors
      if: always()
      run: poetry run pflake8 .
    - name: Run tests
      if: always()
      run: poetry run pytest