name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'textrig/**'
      - 'tests/**'
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
        cache-dependency-path: 'poetry.lock'
    - name: Install dependencies
      run: poetry install
    - name: Cancel on setup error
      if: failure()
      uses: andymckay/cancel-action@0.2
    - name: Run tests
      if: always()
      run: poetry run pytest
