name: TextRig Server Tests

on:
  push:
    branches:
      - main
    paths:
      - 'server/src/**'
      - 'server/tests/**'
      - 'server/setup.cfg'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        cache: 'pip'
        cache-dependency-path: 'server/requirements.txt'
    - id: install-deps
      name: Install dependencies
      run: pip install -r requirements.txt
    - id: check-style
      name: Run style checks
      run: flake8 src tests
    - id: run-tests
      name: Run tests
      run: pytest --cov=src --cov-config=.coveragerc tests/