/* tslint:disable */
/* eslint-disable */
/**
 * TextRig-DEV
 * An online text research platform
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: rick.sanchez@example-textrig-instance.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

