import {
  ArrowBigUp,
  ArrowBigUpDash,
  ArrowDown,
  ArrowDownNarrowWide,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Asterisk,
  Blocks,
  Bold,
  Bookmark,
  BookmarkPlus,
  BookOpenText,
  ChartColumn,
  Check,
  ChevronFirst,
  ChevronLast,
  CircleCheck,
  CircleX,
  Clipboard,
  ClipboardPaste,
  Code,
  CornerDownLeft,
  Delete,
  Download,
  Droplet,
  DropletOff,
  EllipsisVertical,
  ExternalLink,
  File,
  FileQuestionMark,
  FileText,
  FileUp,
  FileX,
  Flag,
  FlagOff,
  FoldVertical,
  Funnel,
  GitCompareArrows,
  Globe,
  GlobeOff,
  HatGlasses,
  Heading,
  Highlighter,
  History,
  Hourglass,
  Image,
  Info,
  Italic,
  Keyboard,
  Languages,
  Layers,
  LibraryBig,
  Link,
  List,
  ListChecks,
  ListOrdered,
  ListX,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MailQuestionMark,
  Mails,
  Megaphone,
  Menu,
  Merge,
  MessageSquareQuote,
  MessageSquareWarning,
  Minus,
  Moon,
  Pause,
  Pencil,
  Pickaxe,
  Play,
  Plus,
  Puzzle,
  Redo,
  RefreshCcw,
  RemoveFormatting,
  Scale,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Settings,
  ShieldCog,
  ShieldMinus,
  ShieldUser,
  Signpost,
  Split,
  SquaresSubtract,
  Star,
  StarOff,
  Sun,
  Tags,
  Target,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignJustify,
  TextAlignStart,
  Toolbox,
  Trash2,
  TriangleAlert,
  Undo,
  UnfoldVertical,
  User,
  UserCog,
  UserPlus,
  Users,
  WandSparkles,
  X,
} from '@lucide/vue';

export {
  BookmarkPlus as AddBookmarkIcon,
  ShieldUser as AdminIcon,
  ShieldCog as AdminSettingsIcon,
  Megaphone as AnnouncementsIcon,
  History as ArchiveIcon,
  ArrowDown as ArrowDownIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUp as ArrowUpIcon,
  Asterisk as AsteriskIcon,
  Delete as BackspaceIcon,
  CircleX as BlockCircleIcon,
  BookOpenText as BookIcon,
  Bookmark as BookmarkIcon,
  ArrowBigUpDash as CapsLockIcon,
  ListChecks as CheckAllIcon,
  CircleCheck as CheckCircleIcon,
  Check as CheckIcon,
  X as ClearIcon,
  Code as CodeIcon,
  Droplet as ColorIcon,
  DropletOff as ColorOffIcon,
  MessageSquareWarning as CommentIcon,
  GitCompareArrows as CompareIcon,
  FoldVertical as CompressIcon,
  Clipboard as CopyIcon,
  Highlighter as CorrectionNoteIcon,
  SquaresSubtract as CoverageIcon,
  Moon as DarkModeIcon,
  Trash2 as DeleteIcon,
  FileText as DescIcon,
  Download as DownloadIcon,
  Pencil as EditIcon,
  CircleX as ErrorIcon,
  UnfoldVertical as ExpandIcon,
  ExternalLink as ExternalLinkIcon,
  File as FileOpenIcon,
  FileQuestionMark as FileQuestionMarkIcon,
  Funnel as FilterIcon,
  TextAlignCenter as FormatAlignCenterIcon,
  TextAlignJustify as FormatAlignJustifyIcon,
  TextAlignStart as FormatAlignLeftIcon,
  TextAlignEnd as FormatAlignRightIcon,
  Bold as FormatBoldIcon,
  RemoveFormatting as FormatClearIcon,
  Italic as FormatItalicIcon,
  List as FormatListBulletedIcon,
  ListOrdered as FormatListNumberedIcon,
  Menu as HamburgerMenuIcon,
  Heading as HeadingIcon,
  Minus as HorizontalRuleIcon,
  Hourglass as HourglassIcon,
  Image as ImageIcon,
  Info as InfoIcon,
  Blocks as IntegratePatchIcon,
  Keyboard as KeyboardIcon,
  CornerDownLeft as KeyboardReturnIcon,
  Languages as LanguagesIcon,
  Scale as LegalIcon,
  ListOrdered as LevelsIcon,
  Sun as LightModeIcon,
  Link as LinkIcon,
  LogIn as LoginIcon,
  LogOut as LogoutIcon,
  Toolbox as MaintenanceIcon,
  UserCog as ManageAccountIcon,
  Merge as MergeIcon,
  Mail as MessageIcon,
  MailCheck as MessageReadIcon,
  Mails as MessagesIcon,
  MailQuestionMark as MessageUnreadIcon,
  Minus as MinusIcon,
  EllipsisVertical as MoreIcon,
  UserPlus as NewUserIcon,
  FileX as NoContentIcon,
  SearchX as NothingFoundIcon,
  ClipboardPaste as PasteIcon,
  Split as PatchIcon,
  Pause as PauseIcon,
  Play as PlayIcon,
  Plus as PlusIcon,
  HatGlasses as PrivacyIcon,
  Flag as ProposedIcon,
  Globe as PublicIcon,
  GlobeOff as PublicOffIcon,
  MessageSquareQuote as QuoteIcon,
  Redo as RedoIcon,
  RefreshCcw as RefreshIcon,
  Layers as ResourceIcon,
  Target as ScoreIcon,
  Search as SearchIcon,
  SearchCheck as SearchResultsIcon,
  Puzzle as SegmentsIcon,
  Send as SendIcon,
  Settings as SettingsIcon,
  ArrowBigUp as ShiftIcon,
  ChevronLast as SkipNextIcon,
  ChevronFirst as SkipPreviousIcon,
  ArrowDownNarrowWide as SortIcon, Star as StarIcon, StarOff as StarOffIcon, ChartColumn as StatsIcon, Tags as TagsIcon,
  Pickaxe as TaskIcon,
  LibraryBig as TextsIcon,
  Signpost as TourIcon,
  ListX as UncheckAllIcon,
  Undo as UndoIcon,
  FlagOff as UnproposedIcon, FileUp as UploadIcon,
  ShieldMinus as UserDowngradeIcon,
  User as UserIcon,
  Users as UsersIcon,
  MailCheck as VerifiedUserIcon,
  WandSparkles as WandIcon,
  TriangleAlert as WarningIcon
};
